// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.3
// source: testdata/pb/ts.proto

package pb

import (
	custom "github.com/tgulacsi/oracall/custom"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *custom.Timestamp   `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Tss []*custom.Timestamp `protobuf:"bytes,2,rep,name=tss,proto3" json:"tss,omitempty"`
}

func (x *Ts) Reset() {
	*x = Ts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_pb_ts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ts) ProtoMessage() {}

func (x *Ts) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_pb_ts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ts.ProtoReflect.Descriptor instead.
func (*Ts) Descriptor() ([]byte, []int) {
	return file_testdata_pb_ts_proto_rawDescGZIP(), []int{0}
}

func (x *Ts) GetTs() *custom.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Ts) GetTss() []*custom.Timestamp {
	if x != nil {
		return x.Tss
	}
	return nil
}

var File_testdata_pb_ts_proto protoreflect.FileDescriptor

var file_testdata_pb_ts_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x02, 0x54,
	0x73, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x2c, 0x0a,
	0x03, 0x74, 0x73, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x74, 0x73, 0x73, 0x42, 0x30, 0x5a, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x67, 0x75, 0x6c, 0x61, 0x63,
	0x73, 0x69, 0x2f, 0x6f, 0x72, 0x61, 0x63, 0x61, 0x6c, 0x6c, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testdata_pb_ts_proto_rawDescOnce sync.Once
	file_testdata_pb_ts_proto_rawDescData = file_testdata_pb_ts_proto_rawDesc
)

func file_testdata_pb_ts_proto_rawDescGZIP() []byte {
	file_testdata_pb_ts_proto_rawDescOnce.Do(func() {
		file_testdata_pb_ts_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_pb_ts_proto_rawDescData)
	})
	return file_testdata_pb_ts_proto_rawDescData
}

var file_testdata_pb_ts_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testdata_pb_ts_proto_goTypes = []interface{}{
	(*Ts)(nil),                  // 0: pb.Ts
	(*custom.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_testdata_pb_ts_proto_depIdxs = []int32{
	1, // 0: pb.Ts.ts:type_name -> google.protobuf.Timestamp
	1, // 1: pb.Ts.tss:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_testdata_pb_ts_proto_init() }
func file_testdata_pb_ts_proto_init() {
	if File_testdata_pb_ts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_pb_ts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_pb_ts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_pb_ts_proto_goTypes,
		DependencyIndexes: file_testdata_pb_ts_proto_depIdxs,
		MessageInfos:      file_testdata_pb_ts_proto_msgTypes,
	}.Build()
	File_testdata_pb_ts_proto = out.File
	file_testdata_pb_ts_proto_rawDesc = nil
	file_testdata_pb_ts_proto_goTypes = nil
	file_testdata_pb_ts_proto_depIdxs = nil
}
